### ISSUE TITLE
IE 7 and 8, time done is not showing up

### ISSUE THREAD

**Issue by dusanko1** [YahooArchive/boomerang#25]
Hi,

I have the code attached on the bottom. Basically copied from the help and your pages. It works fine in FireFox, but in IE it says that t_done is undefined, and it never shows me the time. I tried on IE 8 and IE7. The code is sitting inside of an MVC3 application w/ Razor. I included the entire page's code, just in case I'm doing something wrong..

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>SomeOtherPage</title>
</head>
<body>
    Page #2.

```
<div>
    <p id="results"></p>


    <script src="../../Scripts/Boomerang/boomerang.js" type="text/javascript"></script>
    <script type="text/javascript">
        alert('aa');
        BOOMR.subscribe('before_beacon', function (o) {
            alert('aaa');
            var html = "";
            if (o.t_done) { html += "This page took " + o.t_done + "ms to load<br>"; }
            else { html += "We are missing the load time for some reason.. Done is not hitting.. <br />"; }

            if (o.bw) { html += "Your bandwidth to this server is " + parseInt(o.bw / 1024) + "kbps (&#x00b1;" + parseInt(o.bw_err * 100 / o.bw) + "%)<br>"; }
            if (o.lat) { html += "Your latency to this server is " + parseInt(o.lat) + "&#x00b1;" + o.lat_err + "ms<br>"; }

            document.getElementById('results').innerHTML = html;

            alert(o.t_done);
        });
    </script>
</div>

@(Html.ActionLink("Some Other Page", "SomeOtherPage"))
```

</body>
</html>

<script type="text/javascript">
    //$(document).ready(function () {
        alert('a');
        BOOMR.init({
            user_ip: '10.0.0.1',
            BW: {
                base_url: '../../Content/Images/',
                cookie: 'HOWTO-BA'
            },
            RT: {
                cookie: 'HOWTO-RT'
            }
        });
    //});

</script>

**Comment by djscoutmaster** [comment]
Ditto. Im seing the same issue. I would also add that im not getting the latency on IE8

**Comment by bluesmoon** [comment]
IE 7 and 8 don't have the navtiming api, so they need 2 pages to send a beacon.  I run the code on my own server, and I see beacons coming in from IE6, 7, 8 and 9 although the majority are from 9, about 25% are from 8 and 10% from 7.

**Comment by bluesmoon** [comment]
Just confirmed that IE7 works as expected.

**Comment by bluesmoon** [comment]
verified that IE8 works as expected.
