### ISSUE TITLE
Cannot set cookie in IE

### ISSUE THREAD

**Issue by solarice** [YahooArchive/boomerang#28]
I'm getting the following error in IE:

LOG: boomerang.rt: [error] cannot set start cookie

I found that commenting out these lines resolves the issue:

```
            ((typeof domain !== "undefined") ? "; domain="
                    + (domain !== null ? domain : impl.site_domain ) : "") +
```

in the debugger: impl.site_domain = "localhost"

Any suggestions?

**Comment by bluesmoon** [comment]
boomerang isn't designed to work against localhost.  You need a fully qualified domain name.  Create an alias for your host in /etc/hosts and use that instead.  Perhaps something like localhost.localdomain would work.
