### ISSUE TITLE
Console output doesn't work for iPhone/iPad

### ISSUE THREAD

**Issue by solarice** [YahooArchive/boomerang#44]
I get a warning here:

else if(typeof console !== "undefined" && typeof console.log !== "undefined") {
    boomr.log = function(m,l,s) { console.log(s + ": [" + l + "] ", m); };
}

patched temporary by replacing the last comma with a plus operator within the console.log function reducing the number or args to 1. I don't know the best way to fix. Any suggestions?

**Comment by bluesmoon** [comment]
That fix is probably sufficient.  `console.log` is supposed to concatenate multiple arguments with a space between them, and coerce all of them into strings.  Since all arguments are strings anyway, this is the same as just adding a `+`

**Comment by solarice** [comment]
Ok great! Thanks.
