### ISSUE TITLE
Getting negative values for t_done with angularjs plugin

### ISSUE THREAD

**Issue by rajamadhavan** [YahooArchive/boomerang#52]
Hi,
  I am using boomerangjs with angular plugin. My build includes rt, bw and angular plugins. The version is latest from git. For specific angular soft navigation changes, i am getting t_done as negative on the beacon received back.  Please find below one of the events converted to key/value pairs. Its not always but only for specific soft navigation urls.  I am using it from a local browser, so i know the response is fairly quick but don't understand how it can be negative. 

Mon Jul 25 11:11:53 2016 :  rt_start=manual v=0.9 vis_st=visible ua_plt=Linux_x86_64 ua_vnd=Google_Inc. bw=44368532 bw_err=24730676.15 lat=13 lat_err=6.96 bw_time=1469425309 nu=http://127.0.0.1/app/xxxxx/xxxxxxx rt_tstart=1469425312313 rt_bstart=1469425305236 rt_end=1469425304810 **t_done=-7503** r=http://127.0.0.1/XYZ u=http://127.0.0.1/app/xxxxx/xxxxxxx-*?_g_(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a_(tab:indexedFields) http_initiator=spa 

I would like to understand on what conditions, t_done can get back a negative value? I am seeing this behaviour only while using it with angular plugins.  

-Raja

**Comment by rajamadhavan** [comment]
Moved the issue to the new dev location https://github.com/SOASTA/boomerang/issues/100

Thanks
-Raja

**Comment by bluesmoon** [comment]
Please also close the issue here.
